project:
  type: website
  output-dir: docs

website:
  title: "Home"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: learning.qmd
        text: Learning Progress

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

